development:
  adapter: mysql
  database: cucumber_101_app_development
  host: localhost
  encoding: utf8
  username: root
  password:

test: &TEST
  adapter: mysql
  database: cucumber_101_app_test
  host: localhost
  encoding: utf8
  username: root
  password:

cucumber:
  <<: *TEST